email_functionality/urls.py
from django.urls import path
from .views import DashboardView, DraftsView, UpdateMailView,delete_mail, WriteMail, MailDetailsView

app_name = 'email_functionality'

urlpatterns = [
    path('', DashboardView.as_view(), name='dashboard'),
    path('write_mail/', WriteMail.as_view(), name='write_mail'),
    path('delete_mail/<int:pk>',delete_mail, name='delete'),
    path('update_mail/<int:pk>', UpdateMailView.as_view(), name='update'),
    path('details/<int:pk>/', MailDetailsView.as_view(), name='details'),
    path('drafts/', DraftsView.as_view(), name='drafts')
]
# Create your views here.

email_sender/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('email_functionality/', include('email_functionality.urls'))
]

users/urls.py
from django.urls import path
from .views import HomepageView, CustomLoginView, RegistrationView
from django.contrib.auth.views import LogoutView

app_name = 'users'

# Defining urls for creating users and handling authentications
urlpatterns = [
    path('', HomepageView.as_view(), name='homepage'),
    path('login', CustomLoginView.as_view(), name='login'),
    path('registration', RegistrationView.as_view(), name='register'),
    path('logout', LogoutView.as_view(), name='logout')
]

email_functionality/models.py
from django.db import models
from django.contrib.auth.models import User


# Creating a model to store the mail data
class Mails(models.Model):
    id = models.IntegerField(primary_key=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    subject = models.CharField(max_length=200, null=True, blank=True)
    body = models.CharField(max_length=5000, null=True, blank=True)
    sender = models.EmailField()
    recipient = models.EmailField()
    status = models.CharField(max_length=20)
    date_time = models.DateTimeField(auto_now_add=True)

users/models.py
from django.db import models

# Create your models here.

email_functionality/forms.py
from django import forms
from .models import Mails


# Inheriting from ModelForms to create a form linked to the model class I have defined
class WriteMailForm(forms.ModelForm):
    status = forms.CharField(widget=forms.HiddenInput)
    body = forms.CharField(label='Body', max_length=1000, widget=forms.Textarea)

    class Meta:
        model = Mails
        fields = ('recipient', 'subject', 'body', 'status')

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


# Defining a custom registration form
class CustomRegistrationForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2',)

email_functionality/views.py
from django.views.generic import ListView, UpdateView, DeleteView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import FormView
from .forms import WriteMailForm
from .models import Mails
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy, reverse
from django.http import JsonResponse
from django.core.mail import send_mail
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404


# This view handles the dashboard view
class DashboardView(LoginRequiredMixin, ListView):
    template_name = 'email_functionality/dashboard.html'  # Referring to the Html template
    context_object_name = 'emails'  # this is the name of the query set

    def get_queryset(self):
        user = self.request.user  # setting user variable to the logged in user
        return Mails.objects.filter(user=user)  # returning the mails related to the user


# This function displays the mails saved as drafts
class DraftsView(LoginRequiredMixin, ListView):
    template_name = 'email_functionality/drafts_view.html'  # Referring to Html templates
    context_object_name = 'emails'  # This is the query set name

    def get_queryset(self):  # Getting the query set with this function
        user = self.request.user  # specifying the user to the currently logged in user
        return Mails.objects.filter(user=user, status='draft')  # Returning users drafts


# This function displays the mails and details
class MailDetailsView(LoginRequiredMixin, DetailView):
    model = Mails  # Specifying model
    template_name = 'email_functionality/mail_details.html'  # Referring to Html template
    context_object_name = 'mail'  # Specifying the query set name


# This function displays form to write mail
class WriteMail(LoginRequiredMixin, FormView):
    template_name = 'email_functionality/write_mail.html'  # Referring to Html template
    form_class = WriteMailForm  # Defining the class of forms. This has been imported from the forms file

    def form_valid(self, form):  # Handles form_validation
        data = form.cleaned_data  # Getting form data
        # Creating and instance of the model
        mail_instance = Mails.objects.create(user=self.request.user,
                                             subject=data['subject'],
                                             recipient=data['recipient'],
                                             body=data['body'],
                                             status=data['status'],
                                             sender=self.request.user.email)

        # Calling django's built in send_mail function to send the mail to the email address provided
        try:
            send_email(mail_instance)
        except Exception as e:
            return HttpResponseRedirect(reverse('email_functionality:dashboard'),
                                        {'error': e}
                                        )
        # Redirecting to the dashboard view
        return HttpResponseRedirect(reverse('email_functionality:dashboard'))


# This view handles the update functionality
class UpdateMailView(LoginRequiredMixin, UpdateView):
    model = Mails  # Referring to the model class
    form_class = WriteMailForm  # referring to the form class
    template_name = 'email_functionality/update_mail.html'  # name of the template to display
    success_url = reverse_lazy('email_functionality:dashboard')  # url to redirect

    def form_valid(self, form):
        # Getting the updated subject
        updated_subject = form.cleaned_data['subject']
        # getting the updated body
        updated_body = form.cleaned_data['body']

        # Getting the existing mail
        mail_instance = self.get_object()
        mail_instance.subject = f'{updated_subject} (edited)'
        mail_instance.body = updated_body

        # Saving the changes within my database
        mail_instance.save()

        # Sending the updated mail to the recipient
        send_email(mail_instance)
        # Returning this so that the default behaviour of updating also takes place
        return super().form_valid(form)


@login_required
def delete_mail(request, pk):
    if request.method == 'POST':
        # Filter the mail instance based on the logged-in user
        mail_instance = get_object_or_404(Mails, id=pk, user=request.user)

        # Deleting the selected mail
        mail_instance.delete()

        # Returning a JSON response with a success message
        return JsonResponse(
            {'message': 'The mail was deleted successfully', 'redirect_url': reverse('email_functionality:dashboard')})
    else:
        # Returning a JSON response with the error
        return JsonResponse({'error': 'Invalid request method'}, status=405)


def send_email(mail_instance):
    send_mail(subject=mail_instance.subject,
              message=mail_instance.body,
              from_email=mail_instance.sender,
              recipient_list=[mail_instance.recipient],
              fail_silently=False  # Set this to True if you want to suppress email sending errors
              )

users/views.py
from django.views.generic import TemplateView, CreateView
from django.contrib.auth.views import LoginView
from django.urls import reverse_lazy
from .forms import CustomRegistrationForm


# Redirects user to homepage
class HomepageView(TemplateView):
    template_name = 'users/homepage.html'


# Handles the login functionality
class CustomLoginView(LoginView):
    template_name = 'users/login.html'


# Handles the registration View
class RegistrationView(CreateView):
    template_name = 'users/registration.html'
    form_class = CustomRegistrationForm
    success_url = reverse_lazy('users:login')

email_functionality/templates/email_functionality/dashboard.html
{% extends 'layout.html' %}
{% block head %}
<title>Dashboard</title>
{% load static %}
{% endblock %}

{% block body %}

<!-- Checking if there are any errors -->
{% if error %}
<h1>There was and error:
    Error: {{ error }}</h1>
{% endif %}

<!-- Displaying all the mails which the user has sent -->
<div id="mail_list">
    <h1>Welcome!</h1>
    {% if emails %}
    <h1>You have sent the following mails</h1>
    <ul>

        {% for mail in emails %}
        {% if mail.status == 'send' %}
        <li><a href="{% url 'email_functionality:details' pk=mail.id %}">
            {{mail.subject}} : {{mail.recipient}} ------------------ {{mail.date_time}}
        </a>
        </li>
        {% endif %}
        {% endfor %}

    </ul>
    <!-- If the user has sent no mails then displaying this -->
    {% else %}
    <h2>You have sent no mails</h2>.
    {% endif %}
</div>

<!-- Giving the user the option to write new mails -->
<div id="write_mail">
    <h2>Click here to send some</h2>
    <a href="{% url 'email_functionality:write_mail'%}">
        <button>
            Write Mail
        </button>
    </a>
</div>

<!-- Displaying all the mails the User has saved as draft -->
<div id="mail_drafts">
    <h2>Click here to view your drafts</h2>
    <a href="{% url 'email_functionality:drafts' %}">
        <button id="draft">Drafts</button>
    </a>
</div>
<br>

<!-- Giving the option to logout -->
<div id="logout">
    <h3>You can logout from here</h3>
    <a href="{% url 'users:logout' %}">
        <button> Logout</button>
    </a>
</div>
{% endblock %}

email_functionality/templates/email_functionality/drafts_view.html
{% extends 'layout.html' %}
{% block head %}
<title> Drafts</title>
{% endblock %}

{% block body %}
<h1>Drafts</h1>

<!-- This div displays all the mails the user has saved as draft -->
<div id="drafts_list">
    <ul>
        {% for mail in emails %}
        {% if mail.status == 'draft' %}
        <li>
            <a href="{% url 'email_functionality:details' pk=mail.id %}">
                {{mail.subject}} : {{mail.recipient}} ------------------ {{mail.date_time}}
            </a>
        </li>
        {% endif %}
        {% empty %}
        <li><h2>You have no drafts</h2></li>
        {% endfor %}
    </ul>
</div>

<!-- This div takes user back to previous page -->
<div id="back">
    <h3>Click here to go back</h3>
    <!-- Using javascript to be able to go back -->
    <a href="javascript:history.back()">
        <button>Back</button>
    </a>
</div>


{% endblock %}

email_functionality/templates/email_functionality/mail_details.html
{% extends 'layout.html' %}
{% block head %}
<title>Details</title>
{% load static %}
<!-- Linking JQuery library for making asynchronous requests -->
<script src="https://code.jquery.com/jquery-3.7.1.min.js"
        integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo="
        crossorigin="anonymous"></script>

<!-- Linking my own js file to handle prompts for deleting mails -->
<script src="{% static 'js/delete_mail.js' %}"></script>

<script> var csrfToken = '{{ csrf_token }}'</script>
{% endblock %}

{% block body %}
<!-- Displaying all the details of the mail -->
<div id="mail_details">
    <h1>The details of your mail are as under</h1>
    <div><h4>Sent by: {{mail.user}}</h4></div>
    <div><h4>Sent to : {{mail.recipient}}</h4></div>
    <div><h4>Sent on : {{mail.date_time}}</h4></div>
    <div><h4>Subject : {{mail.subject}}</h4></div>
    <div><h4>Body : {{mail.body}}</h4></div>
    <div><h4>Status : The mail is {{mail.status}}</h4></div>
</div>

<!-- Adding option to go back to update mail -->
<div id="update">
    <h4>Click here to Update the mail</h4>
    <a href="{% url 'email_functionality:update' pk=mail.id %}">
        <button>
            Update
        </button>
    </a>
</div>

<!-- Adding option to go back to delete the mail -->
<div>
    <h4>Click here to Delete the mail</h4>
    {% csrf_token %}
    <input type="hidden" id="delete" data-mail-url="{% url 'email_functionality:delete' pk=mail.id %}">
        <button id="delete_button">
            Delete
        </button>

</div>


<!-- Adding option to go back to the previous page -->
<div id="back">
    <h4>Click here to go back</h4>
    <a href="javascript:history.back()">
        <button id="back_button">
            Back
        </button>
    </a>
</div>


{% endblock %}

email_functionality/templates/email_functionality/update_mail.html
{% extends 'layout.html' %}
{% block head %}
<title>Update Mail </title>
{% load static %}
<script src="{% static 'js/update_mail.js' %}"></script>

{% endblock %}
<!-- Displaying the django form -->
{% block body %}
<h1>Update Mail</h1>
<p>Note:This wont update the old mail but send another updated version of the mail with '(edited)' in the subject </p>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Change</button>
</form>

<!-- Adding option to go back to the previous page -->
<div id="back">
    <h4>Click here to go back</h4>
    <a href="javascript:history.back()">
        <button id="back_button">
            Back
        </button>
    </a>
</div>
{% endblock %}

email_functionality/templates/email_functionality/write_mail.html
{% extends 'layout.html' %}
{% block head %}
<title>Compose</title>
{% load static %}
<script src="{% static 'js/write_mail_script.js' %}"></script>
{% endblock %}

{% block body %}
<!-- Displaying the django-form for writing mail -->
<form id="myform" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="button" id="Send" value="Send">
    <input type="button" id="Draft" value="Draft">
</form>

<!-- This div gives option to go back -->
<div id="back">
    <h3>Click here to go back</h3>
    <a href="javascript:history.back()">
        <button>Back</button>
    </a>
</div>

{% endblock %}

email_sender/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block head %}
    {% load static %}
    <link rel="stylesheet"type="text/css" href="{% static 'css/style.css' %}" >
    {% endblock %}
</head>
<body>
    {% block body %}
    {% endblock %}

</body>
</html>

templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" >

    {% block head %}
    {% endblock %}
</head>
<body>
    {% block body %}
    {% endblock %}

</body>
</html>

users/templates/users/homepage.html
{% extends 'layout.html' %}

{% block head %}
<title>Homepage</title>
{% endblock %}

{% block body %}
<h1>Hey</h1>
<!-- Displaying the option to register -->
<div>If you are a new user. Click Here:
<a href="{% url 'users:register' %}">
    <button>
        Register
    </button>
</a>
</div>
<br>
<br>
<!-- Displaying the option to login -->
<div>Already have an account. Click Here:
<a href="{% url 'users:login' %}">
    <button>
        Login
    </button>
</a>
</div>
{% endblock %}

users/templates/users/login.html
{% extends 'layout.html' %}
{% block head %}
<title>Login</title>
{% endblock %}

{% block body %}
<form method="post">
    <!-- Displaying the django-form for logging in -->
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Login">
</form>
{% endblock %}

users/templates/users/registration.html
{% extends 'layout.html' %}
{% block head %}
<title>Registration</title>
{% endblock %}

{% block body %}
<form method="post">
    <!-- Displaying the django-form for registration -->
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Register">
</form>
{% endblock %}